---
--- Generated by EmmyLua(https://github.com/EmmyLua)

---@class DataStoreModuleOption
---@field data table
---@field manager table<string,function<table>> 
---@field getters table<string,function<table>>
---@field setters table<string,function<table, table>>
---@field callbacks table<string,function>
local DataStoreModuleOption = class("DataStore.Deprecated.DataStoreModuleOption")

---beforeWarp
function DataStoreModuleOption:beforeWarp()
end

---afterWarp
function DataStoreModuleOption:afterWarp()
end

return DataStoreModuleOption