---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---

---@class UIAssetHelper
local UIAssetHelper = class("UIAssetHelper")

function UIAssetHelper.createUIObject(assetName,callback)
    C_ResFunc.InstantiateAsync(assetName,function(assetName, asset, duration, userData)
        callback(asset)
    end,function(assetName, status, errorMessage, userData)
        callback(nil)
    end);
end

function UIAssetHelper.destroyUIObject(gameObject,callback)
    UnityEngine.Object.Destroy(gameObject)
end

function UIAssetHelper.onOpening(uiType,pageName)
end

function UIAssetHelper.onOpened(uiType,pageName,result)
end

return UIAssetHelper