--- UI管理器附件基类
--- Generated by EmmyLua(https://github.com/EmmyLua)
---------------------------------------------------------------------------------------


---@class UIAuxiliaryBase
local UIAuxiliaryBase = class("UIAuxiliaryBase")


function UIAuxiliaryBase:update()
    
end

return UIAuxiliaryBase