---
--- Generated by EmmyLua(https://github.com/EmmyLua)

---@class UIWidgetFactory
local UIWidgetFactory = class("UIWidgetFactory")

function UIWidgetFactory:ctor()
    
end

---registerAssetHelperClass 注册一个AssetHelper的class给UI管理器，UI管理器通过AssetHelper来创建和删除UI所需GameObject对象
---@param assetHelperClass Class
function UIWidgetFactory:registerAssetHelperClass(assetHelperClass)
    self.assetHelper = assetHelperClass
end


function UIWidgetFactory:LoadAndCreatePanelAsync(assetPath,callback,panelCls)
    local this = self
    if type(panelCls) == "string" then
        panelCls = require(panelCls)
        if panelCls == nil then
            error("NFU Panel Bind","panelCls not exist!")
        end
    end
    
    ---@type UIWidgetBase
    local panelInst = nil
    if panelCls~= nil then
        panelInst = panelCls.new()
    end
    
    self.assetHelper.createUIObject(assetPath, function(gameObject)
        if panelInst and panelInst.destroyed then 
            this.assetHelper.destroyUIObject(gameObject) 
            return
        end
        panelInst = this:BindPanelWithGameObject(gameObject,panelInst)
        panelInst.eventBus:addListener("UIPanelDestroyed",function()
            this.assetHelper.destroyUIObject(gameObject)
        end)
        if callback then callback(panelInst) end
    end)
    
    return panelInst
end 


function UIWidgetFactory:BindPanelWithGameObject(gameObject,panelInst)
    local uiExpansion = nil
    if C_UIExpansion then
        uiExpansion = gameObject:GetComponent(typeof(C_UIExpansion))
    end
    if uiExpansion == nil then
        error("NFU Panel Bind","Not a Bindable GameObject, Please Add UIExpansion Component First")
    end


    if type(panelInst) == "string" then
        local panelCls= require(panelInst)
        if panelCls == nil then
            error("NFU Panel Bind","panelCls not exist!"..panelInst)
        end
        panelInst = panelCls.new()
    end

    
    if panelInst == nil then
        local panelCls=  require(uiExpansion.LuaBindPath)
        if panelCls == nil then
            error("NFU Panel Bind","panelCls not exist!"..uiExpansion.LuaBindPath)
        end
        panelInst = panelCls.new()
    end
    
    panelInst:setExpansion(uiExpansion)
    panelInst:created(gameObject)
    return panelInst
end

return UIWidgetFactory