---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---

function pairsNFU(tbl)
    local meta = getmetatable(tbl)
    if meta ~=nil and meta.__pairs ~= nil then
        return meta.__pairs(tbl,meta)
    else
        return pairs(tbl)
    end
end

function iterateNFU(tbl)
    local meta = getmetatable(tbl)
    if meta ~= nil and meta.__iterator ~= nil then
        return meta.__iterator()
    else
        return pairs(tbl)
    end
end

function countNFU(tbl)
    local meta = getmetatable(tbl)
    if meta ~= nil and meta.__count ~= nil then
        return meta.__count()
    else
        return table.nums(tbl)
    end
end

function atNFU(tbl, i)
    local meta = getmetatable(tbl)
    if meta ~= nil and meta.__at ~= nil then
        return meta.__at(i)
    else
        return tbl[i]
    end
end