---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---

function safeCall(targetFunc, errorTip)
    local successCall, errorInfo = pcall(targetFunc)
    if not successCall then
        logError(string.format("%s\n%s\n%s",errorTip, errorInfo, debug.traceback()))
    end
    
    return successCall
end
