---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lin_l.
--- DateTime: 2020/11/27 19:28
---

---@class AllianceModule
local AllianceModule = class("Store.AllianceModule", G_DataStoreModuleBase)

function AllianceModule:initialize()
    self._data = {
        tag = "alliance",

        allianceInfo = {
            id = 0
        },

        allianceList1 =
        {
            {
                name = "alliance1",
                level = 12,
            },
            {
                name = "alliance2",
                level = 13,
            },
        },

        ---创建一些显示用假数据
        allianceList = {
            [300001] = {
                name = "alliance1",
                level = 12,
            },
            [300002] = {
                name = "alliance2",
                level = 15,
            },
            [300003] = {
                name = "alliance2",
                level = 18,
            },
        },
        
        ---创建一些显示用的联盟集结假数据
        allianceMassList = {
            [60000001] = {
                name = "Mass1",
                curNum = 12,
                ---是否已参与
                participated = false,
            },
            [60000002] = {
                name = "Mass2",
                curNum = 15,
                ---是否已参与
                participated = false,
            },
            [60000003] = {
                name = "Mass3",
                curNum = 18,
                ---是否已参与
                participated = false,
            },
        }
    }
end

---getAllianceInfo 根据id获取table数据
---@param id number allianceId
function AllianceModule:getAllianceInfoById(id)
    return self._data.allianceList[id]
end

---getMassInfoById 跟进id获取Mass数据
---@param id number massId
function AllianceModule:getMassInfoById(id)
    return self._data.allianceMassList[id]
end

---onAllianceLevelUp 更新等级
---@param id number
---@param level number
function AllianceModule:onAllianceLevelUp(id, level)
    local info = self._data.allianceList[id]
    info.level = level

    self:fireEvent("onAllianceLevelUp", id)
end

---onUpdateParticipatedMassInfo 更新集结数据
---@param data table 集结消息回调
function AllianceModule:onUpdateParticipatedMassInfo(data)
    for k,v in pairs(self._data.allianceMassList) do
        if k == data.massId then
            v.curNum = data.curNum
            v.participated = true
        end
    end

    self:fireEvent("onUpdateParticipatedMassInfo", data.massId)
end

return AllianceModule