---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huanghch.
--- DateTime: 2021/1/13 11:13
---

local CheckerLevelModule = class("Store.CheckerLevelModule", G_DataStoreModuleBase)

function CheckerLevelModule:initialize()
    self._data = {
        tag = "checkerLevel",
        level = 0,
    }
end

function CheckerLevelModule:SetLevel(level)
    self._data.level = level
end

function CheckerLevelModule:GetLevel()
    return self._data.level
end

return CheckerLevelModule