---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wwei.
--- DateTime: 2020/11/3 19:28
---

---@class PlayerModule
local PlayerModule = class("Store.PlayerModule", G_DataStoreModuleBase)

function PlayerModule:initialize()
    self._data = {
        tag = "player",
        playerId = 0,
        rank = 100,
        playerName = "",
        cardList = {
            type = "array"
        },
        race = "",
        level = 0,
        exp = 0,
        courage_trial = 0,
        fight_value = 0,
        actor_limit = 0,
        vipLevel = 0,
        vipPoints = 0,
        mapId = 0,
        birthday = "",
        account = "",
        charge_sn = 0,
        staking_sn = 0,
        id_account = "",
    }
end

function PlayerModule:playerName()
    return self._data.playerName
end

function PlayerModule:cardList()
    return self._data.cardList
end
function PlayerModule:playerLevel()
    return self._data.level
end

function PlayerModule:setPlayerName(data)
    self._data.playerName = data.playerName
    self._data.playerId = data.playerId
end

---@param data PlayerData
function PlayerModule:setPlayerInfo (data)
    self._data.race = data.race
    self._data.level = data.level
    self._data.exp = data.exp
    self._data.courage_trial = data.courage_trial
    self._data.fight_value = data.fight_value
    self._data.actor_limit = data.actor_limit
    self._data.vipLevel = data.vipLevel
    self._data.vipPoints = data.vipPoints
    self._data.mapId = data.mapId
    self._data.birthday = data.birthday
    self._data.account = data.account
    self._data.charge_sn = data.charge_sn
    self._data.staking_sn = data.staking_sn
    self._data.id_account = data.id_account
end

function PlayerModule:setFormationTeam(data)
    for i, v in ipairs(data.actors) do
        self._data.cardList.insert(v)
    end
end

function PlayerModule:UpdateActorAttribute(data)
    for i, v in ipairs(self._data.cardList) do
        if v.actor_guid == data.guid then
            for ii, vv in ipairs(data.attributes) do
                for iii, vvv in ipairs(v.actor_attributes) do
                    if vv.name == vvv.name then
                        self._data.cardList[i].actor_attributes[iii].value = data.attributes[ii].value
                        break
                    end
                end
            end
            return
        end
    end
end

function PlayerModule:UpdateActorDataInt32(data)
    for i, v in ipairs(self._data.cardList) do
        if v.actor_guid == data.guid then
            if data.name == "level" then
                v.actor_property.level = data.values[1]
            end
            return
        end
    end
end

--获取玩家信息
function PlayerModule:getPlayerInfo(data)
    return Api.player:getPlayerInfo():next(function(d)
        self:setPlayerInfo(d)
        return d
    end)
end

-- 获取玩家卡片信息
function PlayerModule:getActorData(data)
    return Api.player:getActorData():next(function(d)
        self:setFormationTeam(d)
        self:fireEvent("updateAllActor", "ok")
        self:fireEvent("updateAllActor2", "ok")
        return d
    end)
end

function PlayerModule:updateActorData(data)
    return Promise.all(
            {
                NetMgr:receive("SyncrolizeActorDataInt32"):next(function(d)
                    print(tag, "10006")
                    self:UpdateActorDataInt32(d)
                    return d
                end),
                NetMgr:receive("DataActorAttribute"):next(function(d)
                    print(tag, "10007")
                    self:UpdateActorAttribute(d)
                    return d
                end)
            })
end

return PlayerModule
