--- UI所使用的所有枚举
--- Generated by EmmyLua(https://github.com/EmmyLua)
---------------------------------------------------------------------------------------

---@class UIEnums
local UIEnums = class("UIEnums")

---@class Enum_UIType
---@field public stack number
---@field public order number
---@field public freedom number
---@field public unique number
local Enum_UIType = {
    stack = 1,
    order = 2,
    freedom = 3,
    unique = 4
}

---@class Enum_UIPageStatus
---@field public opening number 打开中
---@field public closed number 已关闭
---@field public shown number 显示中
---@field public hided number 已隐藏
---@field public opened number 已打开
---@field public notExist number 不存在
local Enum_UIPageStatus = {
    opening = 1,
    created = 2,
    opened = 3,
    shown = 4,
    closed = 5,
    hided = 6,
    notExist = 7,
}

---@class Enum_UIPageMode
---@field public replace number 替换模式
---@field public coexist number 共存模式
---@field public exclusive number 互斥模式
local Enum_UIPageMode = {
    replace = 1,
    coexist = 2,
    exclusive = 3
}

---@type Enum_UIType
UIEnums.PageType = Enum_UIType
---@type Enum_UIPageMode
UIEnums.PageMode = Enum_UIPageMode
---@type Enum_UIPageStatus
UIEnums.PageStatus = Enum_UIPageStatus

return UIEnums