---
--- Generated by EmmyLua(https://github.com/EmmyLua)

local api = {}

---reqAllianceLevelUp 假装发送消息，并收到回调修改数仓数据
---@param id number
---@param level number
function api:reqAllianceLevelUp(id, level)
    print("I pretend to send request")

    local info = Store.alliance:getAllianceInfoById(id)
    local newLevel = info.level + level
    Store.alliance:onAllianceLevelUp(id, newLevel)

    ---协议发送示例
    --L_Net:request("RecruitRequest", reqData):next(function(data)
    --    ---在协议回调中修改数仓
    --    Store.alliance:onAllianceLevelUp(data)
    --end)
end

---reqAllianceMass 假装参与联盟集结，收到回调函数修改数仓数据
---@param massId number 集结id
function api:reqAllianceMass(massId)
    print("I pretend to send request")
    
    local massInfo = Store.alliance:getMassInfoById(massId)
    massInfo.curNum = massInfo.curNum + 1
    massInfo.participated = true
    Store.alliance:onUpdateParticipatedMassInfo(massInfo)
end

---getAllianceMassMaxNum 获取联盟最大集结数，一般会从config中读取
function api:getAllianceMassMaxNum()
    return 30
end

return api