---
--- Generated by EmmyLua(https://github.com/EmmyLua)

local api = {}

---SetSystemLevel 设置系统等级
---@param level number
function api:SetCheckerLevel(level)
    Store.checkerLevel:SetLevel(level)
end

---GetSystemLevel 获取系统等级
function api:GetCheckerLevel()
    return Store.checkerLevel:GetLevel()
end


return api