---
--- Generated by EmmyLua(https://github.com/EmmyLua)

--- local Config = require("UI.Config")
local CheckerConfig = require("Api.CheckerConfig")

local CheckMgr = {}

function CheckMgr:init()
    UIMgr:registerUIChecker("unlockLevelChecker", checkUnlockLevel)
end

function checkUnlockLevel(pageName,option,callback)
    --- 获取系统等级
    --- 从config获取对应page的unlocklevel
    --- 比较然后返回

    local checkerLevel = Api.checkerLevel:GetCheckerLevel()
    local unlockLevel = CheckerConfig[pageName].unlockLevel
    
    if checkerLevel > unlockLevel then
        callback(true)
    else
        print("等级需要高于"..unlockLevel.."才能打开该页面")
        callback(false)
    end
end


return CheckMgr