---
--- Generated by EmmyLua(https://github.com/EmmyLua)

-- 对Page的配置，该处的配置主要用于Checker
-- 目前该处Page的属性只有unlockLevel解锁等级，checkerFunc检查方法
-- 后续可根据实际业务需求自定义配置表


return {
    ["E5_1_A_Page"] = {unlockLevel = 3},
    ["E5_1_B_Page"] = {unlockLevel = 6}
}